import requests from "@/assets/json/requests";
import Thumbnail from "@/components/Thumbnail";
import useFetch from "hooks/useFetch";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import FlipMove from "react-flip-move";
import InfiniteScroll from "react-infinite-scroll-component";

export default function Home({}) {
  const router = useRouter();
  const { genere } = router.query;
  const {
    data: movies,
    error,
    loading,
  } = useFetch(
    "https://api.themoviedb.org/3/trending/movie/day?language=en-US",
    "GET"
  );
  const fetchMoreData = () => {};

  return (
    <div>
      <Head>
        <title>Hulu2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="scrollableDiv">
        {/*Put the scroll bar always on the bottom*/}
        {movies?.length && (
          <InfiniteScroll
            dataLength={movies.length}
            next={fetchMoreData}
            hasMore={true}
            loader={<h4>Loading...</h4>}
            scrollableTarget="scrollableDiv"
          >
            <FlipMove className="px-5 my-10 sm:grid md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
              {movies.map((movie) => (
                <Thumbnail key={movie.id} movie={movie} />
              ))}
            </FlipMove>
          </InfiniteScroll>
        )}
      </div>
    </div>
  );
}

// export async function getServerSideProps(ctx) {
//   const genere = ctx.query.genere;

//   const res = await fetch(
//     `https://api.themoviedb.org/3${
//       requests[genere]?.url || requests.fetchTrending.url
//     }`
//   );
//   const movies = await res.json();
//   return {
//     props: {
//       movies: movies.results,
//     },
//   };
// }
