import ActionMovies from "@/components/ActionMovies";
import ComedeyMovies from "@/components/ComedyMovies";
import DramaMovies from "@/components/DramaMovies";
import LatestMovies from "@/components/LatestMovies";
import ThrillerMovies from "@/components/ThrillerMovies";
import Head from "next/head";

export default function Home({}) {
  return (
    <div className="">
      <Head>
        <title>MovieFlix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-[1270px] mx-auto relative mt-[-120px] z-[999] px-3">
        <LatestMovies />
      </div>
      <div className="max-w-[1270px] mx-auto mt-[3.5rem]">
        <ActionMovies />
      </div>
      <div className="max-w-[1270px] mx-auto mt-[3.5rem]">
        <ComedeyMovies />
      </div>
      <div className="max-w-[1270px] mx-auto mt-[3.5rem]">
        <DramaMovies />
      </div>
      <div className="max-w-[1270px] mx-auto mt-[3.5rem]">
        <ThrillerMovies />
      </div>
    </div>
  );
}
