import requests from "@/assets/json/requests";
import Thumbnail from "@/components/Thumbnail";
import Head from "next/head";
import FlipMove from "react-flip-move";

export default function Home({ movies }) {
  return (
    <div>
      <Head>
        <title>Hulu2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FlipMove className="px-5 my-10 sm:grid md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
        {movies.map((movie) => (
          <Thumbnail key={movie.id} movie={movie} />
        ))}
      </FlipMove>
    </div>
  );
}

export async function getServerSideProps(ctx) {
  const genere = ctx.query.genere;

  const res = await fetch(
    `https://api.themoviedb.org/3${
      requests[genere]?.url || requests.fetchTrending.url
    }`
  );
  const movies = await res.json();
  return {
    props: {
      movies: movies.results,
    },
  };
}
